# Generated by Django 5.1.1 on 2026-03-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paypal_transaction_id", models.CharField(max_length=255)),
                ("price_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_purchased", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
