export const CHATBOT_SEND_REQUEST = 'CHATBOT_SEND_REQUEST';
export const CHATBOT_SEND_SUCCESS = 'CHATBOT_SEND_SUCCESS';
export const CHATBOT_SEND_FAIL = 'CHATBOT_SEND_FAIL';
export const CHATBOT_CLEAR_MESSAGES = 'CHATBOT_CLEAR_MESSAGES';
